export const STATION_TYPES = ['circle', 'triangle', 'square', 'diamond'];

export const LINE_COLORS = ['#ef2b24', '#21479b', '#ffd200', '#26a65b', '#8e44ad'];

export const GAME_CONFIG = {
  stationRadius: 12,
  stationHitboxRadius: 60,
  lineWidth: 8,
  selectedLineWidth: 11,
  terminalExtensionLength: 24,
  terminalCapLength: 28,
  terminalHitboxRadius: 34,
  lineHitboxRadius: 34,
  controlPointHitboxRadius: 38,
  trainRadius: 8,
  trainSpeed: 0.0022,
  trainCapacity: 6,
  seatRadius: 3.3,
  trainBodyLength: 42,
  trainBodyHeight: 22,
  passengerAnimMs: 520,
  passengerSpawnMs: 2300,
  stationSpawnMs: 6500,
  stationMinDistance: 230,
  stationSpawnMinDistance: 260,
  stationSpawnMaxDistance: 520,
  visualStationSpacing: 0.88,
  maxStationQueue: 16,
  initialLineLimit: 3,
  initialTrackLimit: 8,
  stationsPerResourceBonus: 4,
  lineBonusEveryStations: 8,
  minZoom: 0.55,
  maxZoom: 2.4,
  panDeadZone: 7,
};
